### ISSUE TITLE
[Meta]: Open source checklist

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#172]
Thanks a lot to @bketelsen, @technosophos, and @tenwall for suggestions here.

Here is an initial list of items we want before releasing Spin as open source:

- [x] publicly available documentation website at `https://spin.fermyon.dev`, running the content from the [docs directory](https://github.com/fermyon/spin/tree/main/docs) on top of Spin (#111)
- [x] re-enabling cross-platform CI 
- [x] introductory blog post
- [x] getting started video (5 mintues) (Spin up your application in 5 minutes!)
- [x] https://github.com/fermyon/fermyon.com/pull/208 (edit: added by @vdice)
- [x] make public: https://github.com/fermyon/spin-fileserver (edit: added by @vdice)
- [x] make public: https://github.com/fermyon/url-shortener (edit: added by @vdice)
- [x] make public: https://github.com/fermyon/spin-kitchensink (edit: added by @vdice)
Anything else we missed?

**Comment by radu-matei** [comment]
The repository is now public, thanks a lot, everyone!
