### ISSUE TITLE
Spin (Re)Factors tracking issue

### ISSUE THREAD

**Issue by lann** [fermyon/spin#2619]
Implementation of Spin Factors ([SIP here](https://github.com/fermyon/spin/pull/2518)) is happening in the `factors` branch.

## Fix known issues

- [x] Fix Grain template:https://github.com/fermyon/spin/issues/2779
- [x] Decide what to do about Swift template: https://github.com/fermyon/spin/issues/2774
- [x] Reimplement `spin up --sqlite-statements` (https://github.com/fermyon/spin/pull/2780)
- [x] Reimplement [some trigger hooks](https://github.com/fermyon/spin/blob/82008342a3ec8de7d0ac6f3850828b463c692160/crates/trigger/src/cli.rs#L388-L390) (@lann)
- [x] Fix broken key-value paths (https://github.com/fermyon/spin/pull/2791)
- [x] Merge pre-factor crates with their factor equivalents
- [ ] #2813 

## Document breaking changes (release notes / doc site where appropriate)
- [ ] `HttpRequestDenied` source
- [ ] https://github.com/fermyon/spin/pull/2723
- [x] https://github.com/fermyon/spin/issues/2552
- [ ] https://github.com/fermyon/developer/issues/1371
- [x] https://github.com/fermyon/developer/issues/1376

## Audit feature parity and compatibility against pre-factors code

> If you do this just list what you've reviewed below whether you find problems or not.

## Integrate factors into spin
- [x] Migrate spin-core wasi features to factor(s) (@lann)
- [x] Migrate host component call sites (e.g. `add_host_component`, `find_host_component_handle`) (@lann)
- [x] Update triggers (document upgrade process?)
  - [x] `http` (mostly complete)
  - [x] `redis`
- [x] Update component loader
  - [x] Integrate with #2673
  - [x] Implement nice error for #2552
  - [x] Port `unsafe-aot-compilation` feature https://github.com/fermyon/spin/pull/2818

## Port host components to factors

- [x] `key-value` (@kate-goldenring)
  - [x] `azure`
  - [x] `redis`
  - [x] `sqlite`
- [x] `llm` (@rylev)
- [x] `outbound-http`
  - [x] `spin` (https://github.com/fermyon/spin/pull/2740)
  - [x] `wasi`
- [x] `outbound-mqtt` (@karthik2804) (https://github.com/fermyon/spin/pull/2722)
- [x] `outbound-mysql` (@karthik2804)
- [x] `outbound-pg` (@calebschoepp)
- [x] `outbound-redis` (@me-diru)
- [x] `sqlite` (@rylev)
- [x] `variables` (@rylev)
  - [x] `env`
  - [x] `vault`
  - [x] `azure` (https://github.com/fermyon/spin/pull/2724)
 
## Integrate factors into new `spin-trigger`

- [x] `wasi`
- [x] `variables`
- [x] `key-value`
- [x] `sqlite`
- [x] `outbound-http`
- [x] `outbound-redis`
- [x] `outbound-mqtt`
- [x] `outbound-pg`
- [x] `outbound-mysql`
- [x] `llm`

**Comment by calebschoepp** [comment]
> - [ ] Merge pre-factor crates with their factor equivalents
@lann I'm picking up this work for `factor-key-value`. A quick search in the codebase suggests this is also needed for `factor-outbound-networking` — I'm less confident in my ability to execute that, but perhaps I'll give it a try and see if I get stuck.

**Comment by lann** [comment]
> I'm picking up this work for `factor-key-value`.

Check with @rylev who has been knee-deep in this crate e.g. https://github.com/fermyon/spin/pull/2791

**Comment by vdice** [comment]
@lann is this ready to be closed out?  It looks like the unchecked docs TODOs above might all be met in https://github.com/fermyon/developer/pull/1396 ?

**Comment by lann** [comment]
Benchmarks runner isn't blocking - we can close this with the docs changes.

**Comment by vdice** [comment]
Closing per https://github.com/fermyon/developer/pull/1396 which covered the remaining docs changes
