### ISSUE TITLE
implement the rest of the spin deploy SIP

### ISSUE THREAD

**Issue by michelleN** [fermyon/spin#484]
- [x] update deploy logic to use hippo client logic from the hippo cli repo -- part of #506, related: https://github.com/deislabs/hippo-cli/pull/133
- [x] update deploy to run on latest version of hippo #506 
- [x] better UX around if a Hippo app or channel already exists #503 -- **Currently we delete the app and that works. We're continually improving this though.**
- [x] better error handling
- [x] figure out and fix how to configure domains for apps deployed via spin deploy command
- [x] smooth out experience around building/pushing bindles from within deploy #508

**Comment by vdice** [comment]
@michelleN Is this ready to be closed out?  Or is there remaining work to be done?

**Comment by michelleN** [comment]
Yes this can be closed. Thank you
