### ISSUE TITLE
[META]: Running fermyon.com using Spin

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#75]
With the new file server (https://github.com/fermyon/spin-fileserver) and the port of Bartholomew (no PR yet, as it would be public), we can run the fermyon.com website locally using Spin, and I think it is in our best interest to run it in production _using_ Spin as soon as possible.

Before doing that, we need to solve a few issues:

-  [x] #70 (unnoticeable for the website, but very annoying) 

- [x] #37 and #42 (we could it as a local app, but we need to use Bindle anyway) 
- [x] #71 (fix available)
- [x] #31 (redirecting both `stdout` and `stderr` to files should work)
- [x] #33
- ~~[ ] #22~~

EDIT: we decided to move ahead with running spin.fermyon.dev using Spin first, and integrate Hippo there.
So #22 is no longer a hard requirement for now, but it will become again for v0.2.0

**Comment by radu-matei** [comment]
[fermyon.com](https://fermyon.com) has been running on Spin for a few months now.
